select 
    code_postal,
    ville_client,
    pays_client,
    client_origin, 
    amo_name,
    rc1_name,
    no_facture,
    product_quantity,
    frame_type_name,
    type_article,
    package_datail_type_name,
    article_name,
    content,
    eye_side,
    prix_achat_catalogue,
    prix_achat_magasin,
    prix_vente_magasin,
    rabais_et_remise_ttc,
    prix_vente_remise_ht * product_quantity as prix_vente_remise_ht,
    ttc_net_sale_price,
    sale_tva_rate,
    package_status,
    package_status_definition,
    proposal_status,
    proposal_status_definition,
    vat_rate,
    ville_magasin, 
    client_invoice_creation_date, 
    package_creation_date,
    visit_creation_date,
    article_code,
    shop_id

from 
{{ ref('int_client_invoices_extended') }} 
union all 
select 
    code_postal,
    ville_client,
    pays_client,
    client_origin, 
    amo_name,
    rc1_name,
    no_facture,
    product_quantity,
    frame_type_name,
    type_article,
    package_datail_type_name,
    article_name,
    content,
    eye_side,
    prix_achat_catalogue,
    prix_achat_magasin,
    prix_vente_magasin,
    rabais_et_remise_ttc,
    prix_vente_remise_ht,
    ttc_net_sale_price,
    sale_tva_rate,
    'Avoir' as package_status,
    'Avoir' as package_status_definition,
    proposal_status,
    proposal_status_definition,
    vat_rate,
    ville_magasin, 
    client_invoice_creation_date, 
    package_creation_date,
    visit_creation_date,
    article_code,
    shop_id

from 
{{ ref('int_credit_notes_invoices_extended') }} 