version: 2

sources:
  - name: optimum
    description: "Raw Optimum data loaded from SFTP ZIP files into BigQuery."
    database: "project-b2a3ecb7-3b81-4883-82d"
    schema: raw_optimum

    tables:
      - name: clients
      - name: shops
        description: "Full shops export."
      - name: articles
        description: "Full articles export."
      - name: articles_types
        description: "Full articles types export."
      - name: frame_types
      - name: clients_invoices
        description: "Incremental client invoices export."
      - name: clients_invoices_details
        description: "Incremental client invoice details export."
      - name: credit_notes_invoices
        description: "les avoirs"
      - name: credit_notes_invoices_details
      - name: packages
        description: "Incremental packages export."
      - name: package_details
        description: "Incremental packages details export."
      - name: packages_details_types
      - name: package_frame_properties
      - name: packages_status
      - name: proposals
      - name: proposals_status
      - name: sellers
      - name: visits
      - name: visits_status