version: 2

sources:
  - name: optimum
    description: "Raw Optimum data loaded from SFTP ZIP files into BigQuery."
    database: "project-b2a3ecb7-3b81-4883-82d"
    schema: raw_optimum

    tables:
      - name: shops
        description: "Full shops export."

      - name: clients_invoices
        description: "Incremental client invoices export."

      - name: clients_invoices_details
        description: "Incremental client invoice details export."

      - name: packages
        description: "Incremental packages export."

      - name: package_details
        description: "Incremental packages details export."
